export const investingTopics: Array<string> = [
  "Introduction",
  "Up Down Bar",
  "Spread",
  "Volume",
  "Close Position",
  "Effort Vs Result",
  "Supply And Demand",
  "No Demand No Supply",
  "Stopping Volume Climaxes",
  "Tests",
  "Shakeout Spring",
  "Upthrust",
  "Absorption",
  "Accumulation",
  "Distribution",
  "Markup Markdown",
  "Background Analysis",
  "Real Charts",
  "Backtesting",
  "Strategy",
  "Risk Management",
];